import "@/app/globals.css";
import { Inter } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Analytics } from "@vercel/analytics/react";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <div className="flex h-screen w-full">
            {/* Sidebar */}
            <AppSidebar />
            {/* Main Content */}
            <div className="flex-1">
              <main className="p-4">{children}</main>
              <Toaster />
              <Analytics />
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
